GET http://localhost:5001/api/v1/health 


###

POST http://localhost:5001/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@laverdad.edu.ph",
  "password": "demopass"
}

### 
GET http://localhost:5001/api/v1/auth/me
Authorization: Bearer {{'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4M2YwMzFjZGJkMGU2MjBjMTg2M2QxZCIsImlhdCI6MTc0OTIyMzc5NSwiZXhwIjoxNzUxODE1Nzk1fQ.8SAOr5kmi6JHiFD0odOn4v3MsG6WlEV1BoeB7FhpmVs'}}


###
POST http://localhost:5001/api/v1/auth/request-password-reset

Content-Type: application/json
{
  "email": "admin@lvcc.edu.ph"
}

